export const SET_DIF_WORDS_SUCCESS = 'SET_DIF_WORDS_SUCCESS';
export const SET_DIF_WORDS_FAILURE = 'SET_DIF_WORDS_FAILURE';
export const SET_DIF_WORDS_STARTED = 'SET_DIF_WORDS_STARTED';
// export const SET_DIF_PAGE = 'SET_DIF_PAGE';
// export const SET_DIF_GROUP = 'SET_DIF_GROUP';
