const SET_GAME_WORDS = 'SET_GAME_WORDS';
// const SET_GRUP_WORDS = 'SET_GRUP_WORDS';
const SET_LEVEL_GAME = 'SET_LEVEL_GAME';

const SET_GRUPWORDS_SUCCESS = 'SET_GRUPWORDS';
const SET_GRUPWORDS_FAILURE = 'SET_GRUPWORDS_FAILURE';
const SET_GRUPWORDS_STARTED = 'SET_GRUPWORDS_STARTED';
const UPDATE_WORD = 'UPDATE_WORD';

export {
  SET_GAME_WORDS,
  SET_LEVEL_GAME,
  SET_GRUPWORDS_STARTED,
  SET_GRUPWORDS_FAILURE,
  SET_GRUPWORDS_SUCCESS,
  UPDATE_WORD,
};
