export const SET_DEL_WORDS_SUCCESS = 'SET_DEL_WORDS_SUCCESS';
export const SET_DEL_WORDS_FAILURE = 'SET_DEL_WORDS_FAILURE';
export const SET_DEL_WORDS_STARTED = 'SET_DEL_WORDS_STARTED';
export const SET_DEL_PAGE = 'SET_DEL_PAGE';
export const SET_DEL_GROUP = 'SET_DEL_GROUP';
export const SET_DEL_WORDS_COUNT = 'SET_DEL_WORDS_COUNT';
