export const SET_AMOUNTSTUDY_WORDS_SUCCESS = 'SET_AMOUNTSTUDY_WORDS_SUCCESS';
export const SET_AMOUNTSTUDY_WORDS_FAILURE = 'SET_AMOUNTSTUDY_WORDS_FAILURE';
export const SET_AMOUNTSTUDY_WORDS_STARTED = 'SET_AMOUNTSTUDY_WORDS_STARTED';
