export const NUMBER_OF_WORDS = 5;
export const NUMBER_OF_PAIRS = 8;
export const SAVANNAH = 'savannah';
export const AUDIO_CALL = 'audiocall';
export const SPRINT = 'sprint';
export const MEMORY = 'memory';
export const CORRECT = 'верно';
export const WRONG = 'неверно';
export const GAME_OVER = 'Конец игры';
