export const SET_STUDY_WORDS_SUCCESS = 'SET_STUDY_WORDS_SUCCESS';
export const SET_STUDY_WORDS_FAILURE = 'SET_STUDY_WORDS_FAILURE';
export const SET_STUDY_WORDS_STARTED = 'SET_STUDY_WORDS_STARTED';
export const SET_AMOUNT_WORDS = 'SET_AMOUNT_WORDS';
